<a href="https://colab.research.google.com/github/timapasechnik/ml_basic/blob/main/HW8_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

У цьому домашньому завданні ми будемо працювати з набором даних Tips. Нижче інформація про нього.

**Про датасет:**

Tips - це датасет, який містить інформацію про рахунки та чайові в ресторані.

**Колонки датасету:**
- `total_bill` - загальна сума рахунку (долари)
- `tip` - розмір чайових (долари)
- `sex` - стать відвідувача (Male/Female)
- `smoker` - чи курить (Yes/No)
- `day` - день тижня (Thur/Fri/Sat/Sun)
- `time` - час відвідування (Lunch/Dinner)
- `size` - розмір групи (кількість людей)

**Джерело:** Оригінальні дані зібрані в одному з американських ресторанів у 1990-х роках. Скачати і переглянути набір даних можна тут: https://www.kaggle.com/datasets/sakshisatre/tips-dataset

А також ми вже вивантажили файл з даними і завантажили вам у Матеріали до цього модуля.




**1. Завантаження та огляд**

Завантажте датасет Tips (Чайові) з файла у матеріалах `tips.csv`.

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перші 5 рядків
- Розмір датасету (shape)
- Назви всіх колонок
- Інформацію про типи даних (info)

In [9]:
import pandas as pd
df = pd.read_csv('tip.csv')

print("Перші 5 рядків")
display(df.head())

print("\nРозмір датасету (shape)")
display(df.shape)

print("\nНазви всіх колонок")
display(df.columns)

print("\nІнформацію про типи даних (info)")
display(df.info())

Перші 5 рядків

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

Розмір датасету (shape)

(244, 7)

Назви всіх колонок

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

Інформацію про типи даних (info)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

None

**2. Базова вибірка даних**

Виберіть та виведіть (кожен пункт оцінюється в 0.5 бала):
- Колонку `total_bill` (загальний рахунок)
- Колонки `total_bill` та `tip` (чайові) разом
- Перші 10 рядків
- Рядок з індексом 5

In [14]:

print("Колонку total_bill (загальний рахунок)")
display(df['total_bill'])

print("\nКолонки total_bill та tip (чайові) разом")
display(df[['total_bill', 'tip']])

print("\nПерші 10 рядків")
display(df.head(10))

print("\nАБО перші 10 рядків")
display(df.iloc[0:10])

print("\nРядок з індексом 5")
display(df.iloc[5])

Колонку total_bill (загальний рахунок)

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

Колонки total_bill та tip (чайові) разом

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

Перші 10 рядків

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

АБО перші 10 рядків

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

Рядок з індексом 5

total_bill     25.29
tip             4.71
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 5, dtype: object

**3. Фільтрація даних**

Відфільтруйте повний набір даних та виведіть (кожен пункт оцінюється в 0.5 бала):
- Всі рахунки більше 20 доларів (`total_bill > 20`)
- Всі відвідувачі-жінки (`sex == 'Female'`)
- Рахунки на вечерю (`time == 'Dinner'`)
- Рахунки на вечерю з сумою чеку більше 30 доларів

Для виведення результатів фільтрації:
- зберегти результат у окрему змінну
- показати кількість записів у відфільтрованому наборі
- вивести перші 5 записів відфільтрованого набору.

In [22]:
print("Всі рахунки більше 20 доларів (total_bill > 20)")
filtr_1 = df[df.total_bill > 20]
display(filtr_1.shape)
display(filtr_1.head())

print("\nВсі відвідувачі-жінки (sex == 'Female')")
filtr_2 = df[df.sex == 'Female']
display(filtr_2.shape)
display(filtr_2.head())

print("\nРахунки на вечерю (time == 'Dinner')")
filtr_3 = df[df.time == 'Dinner']
display(filtr_3.shape)
display(filtr_3.head())

print("\nРахунки на вечерю з сумою чеку більше 30 доларів")
filtr_4 = df[(df.time == 'Dinner') & (df["total_bill"] > 30)]
display(filtr_4.shape)
display(filtr_4.head())

Всі рахунки більше 20 доларів (total_bill > 20)

(97, 7)

   total_bill   tip     sex smoker  day    time  size
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
7       26.88  3.12    Male     No  Sun  Dinner     4

Всі відвідувачі-жінки (sex == 'Female')

(87, 7)

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
11       35.26  5.00  Female     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2
16       10.33  1.67  Female     No  Sun  Dinner     3

Рахунки на вечерю (time == 'Dinner')

(176, 7)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

Рахунки на вечерю з сумою чеку більше 30 доларів

(27, 7)

    total_bill   tip     sex smoker  day    time  size
11       35.26  5.00  Female     No  Sun  Dinner     4
23       39.42  7.58    Male     No  Sat  Dinner     4
39       31.27  5.00    Male     No  Sat  Dinner     3
44       30.40  5.60    Male     No  Sun  Dinner     4
47       32.40  6.00    Male     No  Sun  Dinner     4

---

**4. Описова статистика**

Обчисліть (кожен пункт оцінюється в 0.5 бала):
- Середній розмір рахунку на всьому наборі даних
- Максимальні чайові
- Кількість пропущених значень у всіх колонках
- Скільки в наборі даних рахунків за обіди і за вечері

In [51]:
print("\nСередній розмір рахунку на всьому наборі даних")
print(f"${df['total_bill'].mean().round(2)}")

print("\n===============")
print("Максимальні чайові")
print(f"${df['total_bill'].max()}")

print("\n===============")
print("Кількість пропущених значень у всіх колонках")
display(df.isnull().sum())

print("\n===============")
print("Скільки в наборі даних рахунків за обіди і за вечері")
print(len(df[df.time.isin(['Dinner', 'Lunch'])]))

print("\nСкільки в наборі даних рахунків за обіди")
print(len(df[df.time.isin(['Lunch'])]))

print("\nСкільки в наборі даних рахунків за вечері")
print(len(df[df.time.isin(['Dinner'])]))

Середній розмір рахунку на всьому наборі даних
$19.79

===============
Максимальні чайові
$50.81

===============
Кількість пропущених значень у всіх колонках

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

===============
Скільки в наборі даних рахунків за обіди і за вечері
244

Скільки в наборі даних рахунків за обіди
68

Скільки в наборі даних рахунків за вечері
176

---

**5. Статистика із групуванням**

Обчисліть (кожен пункт оцінюється в 0.5 бала):
- Середній рахунок за статтю (groupby `sex`)
- Середні чайові за днем тижня (groupby `day`)
- Скільки відвідувачів у кожен день

In [64]:
print("\nСередній рахунок за статтю (groupby sex)")
display(df.groupby("sex")['total_bill'].mean().round(2))

print("\n===============")
print("Середні чайові за днем тижня (groupby day)")
display(df.groupby("day")['tip'].mean().round(2))

Середній рахунок за статтю (groupby sex)

sex
Female    18.06
Male      20.74
Name: total_bill, dtype: float64

===============
Середні чайові за днем тижня (groupby day)

day
Fri     2.73
Sat     2.99
Sun     3.26
Thur    2.77
Name: tip, dtype: float64

---

**6. Створення нової колонки**

Створіть нову колонку `tip_percentage` - відсоток чайових від загальної суми рахунку.
Виведіть перші 10 рядків з новою колонкою.

In [68]:
df["tip_percentage"] = (df.tip / df.total_bill).round(2)
display(df.iloc[0:10])

   total_bill   tip     sex smoker  day    time  size  tip_percentage
0       16.99  1.01  Female     No  Sun  Dinner     2            0.06
1       10.34  1.66    Male     No  Sun  Dinner     3            0.16
2       21.01  3.50    Male     No  Sun  Dinner     3            0.17
3       23.68  3.31    Male     No  Sun  Dinner     2            0.14
4       24.59  3.61  Female     No  Sun  Dinner     4            0.15
5       25.29  4.71    Male     No  Sun  Dinner     4            0.19
6        8.77  2.00    Male     No  Sun  Dinner     2            0.23
7       26.88  3.12    Male     No  Sun  Dinner     4            0.12
8       15.04  1.96    Male     No  Sun  Dinner     2            0.13
9       14.78  3.23    Male     No  Sun  Dinner     2            0.22

---

**7. Сортування**

Відсортуйте датасет і виведіть результат сортування в кожному випадку окремо (кожен пункт оцінюється в 0.5 бала):
- За розміром рахунку (зростання)
- За чайовими (спадання)

Додатково виведіть топ-5 найбільших чайових використовуючи метод `nlargest`.

In [76]:
print("За розміром рахунку (зростання)")
display(df.sort_values('total_bill', ascending=True))

print("\n===============")
print("За чайовими (спадання)")
display(df.sort_values('tip', ascending=False))

print("\n===============")
print("топ-5 найбільших чайових")
display(df.nlargest(5, 'tip')['tip'])

За розміром рахунку (зростання)

     total_bill    tip     sex smoker   day    time  size  tip_percentage
67         3.07   1.00  Female    Yes   Sat  Dinner     1            0.33
92         5.75   1.00  Female    Yes   Fri  Dinner     2            0.17
111        7.25   1.00  Female     No   Sat  Dinner     1            0.14
172        7.25   5.15    Male    Yes   Sun  Dinner     2            0.71
149        7.51   2.00    Male     No  Thur   Lunch     2            0.27
..          ...    ...     ...    ...   ...     ...   ...             ...
182       45.35   3.50    Male    Yes   Sun  Dinner     3            0.08
156       48.17   5.00    Male     No   Sun  Dinner     6            0.10
59        48.27   6.73    Male     No   Sat  Dinner     4            0.14
212       48.33   9.00    Male     No   Sat  Dinner     4            0.19
170       50.81  10.00    Male    Yes   Sat  Dinner     3            0.20

[244 rows x 8 columns]

===============
За чайовими (спадання)

     total_bill    tip     sex smoker   day    time  size  tip_percentage
170       50.81  10.00    Male    Yes   Sat  Dinner     3            0.20
212       48.33   9.00    Male     No   Sat  Dinner     4            0.19
23        39.42   7.58    Male     No   Sat  Dinner     4            0.19
59        48.27   6.73    Male     No   Sat  Dinner     4            0.14
141       34.30   6.70    Male     No  Thur   Lunch     6            0.20
..          ...    ...     ...    ...   ...     ...   ...             ...
0         16.99   1.01  Female     No   Sun  Dinner     2            0.06
111        7.25   1.00  Female     No   Sat  Dinner     1            0.14
92         5.75   1.00  Female    Yes   Fri  Dinner     2            0.17
67         3.07   1.00  Female    Yes   Sat  Dinner     1            0.33
236       12.60   1.00    Male    Yes   Sat  Dinner     2            0.08

[244 rows x 8 columns]

===============
топ-5 найбільших чайових

170    10.00
212     9.00
23      7.58
59      6.73
141     6.70
Name: tip, dtype: float64